# Generated by Django 4.1 on 2024-03-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YolovModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('model_path', models.CharField(max_length=255)),
                ('model_acid', models.CharField(max_length=255)),
                ('model_size', models.CharField(max_length=255)),
                ('model_parameter', models.CharField(max_length=255)),
            ],
        ),
    ]
